[package]
name = "calculadora-terminal"
version = "0.1.0"
edition = "2024"
description = "Uma calculadora científica em Rust"
authors = ["Gabriel Blum <gabriel.blum.santos@gmail.com>"]

[dependencies]
clap = { version = "4.0", features = ["derive"] }
eframe = "0.19.0"
egui = "0.19.0"
